#!/bin/sh
INTERVAL=0.9
REMOTE=sams
#REMOTE=lg
#REMOTE=mag

irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_DOWN
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_DOWN
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_DOWN
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_DOWN
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_DOWN
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_UP
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_UP
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_UP
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_DOWN
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_DOWN
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_UP
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_UP
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_DOWN
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_DOWN
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_LEFT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_UP
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_UP
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RIGHT
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_RED
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_DOWN
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_1
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_2
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_3
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_4
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_5
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_6
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_DOWN
sleep $INTERVAL
irsend SEND_ONCE $REMOTE KEY_OK
